# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('menu', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
