# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookmingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
