# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookmingo', '0002_auto_20170313_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cafe_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
