# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookmingo', '0003_auto_20170313_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cafe_name',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
