# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookmingo', '0004_auto_20170313_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cafe_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
