# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookmingo', '0005_auto_20170313_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=10000),
        ),
    ]
